words = ("Apple", "Banana", "Orange", "Grape", "Lemon", "Mango", "Peach", "Pear", "Plum", "Berry",
"House", "Chair", "Table", "Door", "Window", "Shelf", "Floor", "Roof", "Light", "Couch",
"Tiger", "Lion", "Bear", "Horse", "Cow", "Sheep", "Goat", "Pig", "Duck", "Rabbit",
"Train", "Truck", "Plane", "Ship", "Car", "Bus", "Bike", "Boat", "Taxi", "Subway",
"Green", "Black", "White", "Brown", "Purple", "Yellow", "Orange", "Blue", "Pink", "Red",
"Water", "Earth", "Fire", "Wind", "Cloud", "Stone", "Grass", "River", "Mountain", "Ocean",
"Apple", "Clock", "Brush", "Glove", "Plate", "Knife", "Fork", "Broom", "Shirt", "Pants",
"Mouse", "Panda", "Snake", "Frog", "Shark", "Whale", "Eagle", "Zebra", "Llama", "Koala",
"Happy", "Funny", "Quiet", "Lucky", "Quick", "Brave", "Smart", "Kind", "Fast", "Small",
"Pizza", "Bread", "Cheese", "Toast", "Cereal", "Bacon", "Pasta", "Candy", "Cookie", "Donut")

hangman_art = {0: (" | ",
                   "   ",
                   "   ",
                   "   "),
               1: (" | ",
                   " o ",
                   "   ",
                   "   "),
               2: (" | ",
                   " o ",
                   " | ",
                   "   "),
               3: (" | ",
                   " o ",
                   "/| ",
                   "   "),
               4: (" | ",
                   " o ",
                   "/|\\",
                   "   "),
               5: (" | ",
                   " o ",
                   "/|\\",
                   "/  "),
               6: (" | ",
                   " o ",
                   "/|\\",
                   "/ \\"),
               7: (" o ",
                   "/|\\",
                   "/ \\")}